### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by lee-aaron** [lee-aaron/honyomi#1]
# List of Things to Fix
- [ ] Caching of images and manga info
- [ ] Download manga
- [ ] Resolve several promises at a time for manga url
- [ ] Fix drawer slide and improve Reader UI
- [ ] Support filters and search boxes
- [ ] Refactor
- [ ] Test on iOS & Android
